### ISSUE TITLE
Error in PAPI_library_init

### ISSUE THREAD

**Issue by cheshmi** [markoshorro/papi_wrapper#5]
Hello,

I want to use the papi wrapper for a multi-threaded code. 
I could compile it using Ubuntu 20, gcc 9.4. I used the provided shell script to build it. However, when I run the compiled tests, it gives me an error. For example:
```
./test_pw_multithread.o 
/home/kazem/programs/papi_wrapper/lib/papi_wrapper.c FAILED
Line # 356
Error in PAPI_thread_init: PAPI hasn't been initialized yet

```
This happens for all tests (with a different line number).

Any helps will be appreciated. 

----------- Update:
I had multiple PAPI versions in my machine, the problem is solved.

**Comment by markoshorro** [comment]
Glad to hear that ;)

**Comment by cheshmi** [comment]
:) 
BTW, I see you collect counters one by one (`PAPI_add_event`). Don't you think there is a value in collecting multiple counters simultaneously (`PAPI_add_events`)?

**Comment by markoshorro** [comment]
@cheshmi yeah, that is something we thought about in the past. However, each architecture has a concrete number of performance registers available. If you want to measure a large number of events, this hardware limitation complicates life a lot if you don't want to do multiplexing.

We developed this wrapper for measuring relatively small regions of code, and that's why this approach work good as it doesn't add that much runtime even though the measurements are done sequentially.

Does this answer the question?

**Comment by cheshmi** [comment]
Yes, makes sense. 
This wrapper is quite handy. Thanks for making it public.
